version: '3.8'

services:
  # Serviço da Aplicação (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
      # - redis
    networks:
      - laravel-net

  # Servidor Web (Nginx)
  nginx:
    image: nginx:1.25-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8181:80" # Acesse em http://localhost:8080
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

  # Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "33061:3306" # Acesse externamente pela porta 33061 (evita conflito)
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-net

  # Cache (Redis)
  # redis:
  #   image: redis:7-alpine
  #   container_name: laravel_redis
  #   restart: unless-stopped
  #   networks:
  #     - laravel-net

# Redes e Volumes
networks:
  laravel-net:
    driver: bridge

volumes:
  db_data:
    driver: local